- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: group
          widgets:
            - type: calendar
              first-day-of-week: monday
        - type: group
          widgets:
            - type: weather
              location: Chennai, India
              units: metric # alternatively "imperial"
              hour-format: 12h # alternatively "24h"
                # Optionally hide the location from being displayed in the widget
              hide-location: true
        
    - size: full
      widgets:
        - type: videos
          # style: vertical-list
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsd6hP-zzIkCpw8XGw7Osyw # Geerling Engineering
            - UCfpCQ89W9wjkHc8J_6eTbBg # Outdoor Boys
            - UCdBK94H6oZT2Q7l0-b0xmMg # ShortCircuit
            - UCeeFfhMcJa1kjtfZAGskOCA # Tech Linked
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCMiJRAwDNSNzuYeN2uWa0pA # Mrwhostheboss
            - UCWFKCr40YwOZQx8FHU_ZqqQ # Jerryrig Everything
            - UCUQo7nzH1sXVpzL92VesANw # DIY Perks
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
            - UCYO_jab_esuFRV4b17AJtAw # 3Blue1Brown
            - UCcyq283he07B7_KUX07mmtA # Business Insider
            - UCO8DQrSp5yEP937qNqTooOw # Strange Parts
            - UCjSEJkpGbcZhvo0lr-44X_w # Tech Hut
            - UCgbw0F-frjDxvQjzruGRJwg # The Serial Port
            - 
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: hacker-news
            - type: lobsters
            - type: rss
              limit: 20
              collapse-after: 10
              cache: 12h
              feeds:
                - url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
                  title: New York Times
                - url: https://feeds.bbci.co.uk/news/rss.xml
                  title: BBC News
                - url: https://www.reddit.com/r/technology/.rss
                  title: Reddit Technology
                - url: https://www.theverge.com/rss/index.xml
                  title: The Verge
                - url: https://feeds.arstechnica.com/arstechnica/index
                  title: Ars Technica
                - url: https://www.engadget.com/rss.xml
                  title: Engadget

    - size: small
      widgets:
        
        - type: markets
          symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
          markets:
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: TSLA
              name: Tesla
            - symbol: GOOGL
              name: Google
            - symbol: AMZN
              name: Amazon
            - symbol: NVDA
              name: NVIDIA
            - symbol: INTC
              name: Intel
            - symbol: IBM
              name: IBM
            - symbol: QCOM
              name: Qualcomm
            - symbol: HPE
              name: Hewlett Packard Enterprise
        

        

