---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
layout:
  - Bookmarks:
      header: false
      style: row
      columns: 8 

  - Download Tools:
      header: false
      style: column
      row: 3

  - Media Services:
      header: false
      style: column
      row: 3

  - Management:
      header: false
      style: column
      row: 3

  - Utilities:
      header: false
      style: row
      columns: 8

  - Dash:
      header: false
      style: row
      columns: 1

background: 
  image: https://w.wallhaven.cc/full/yq/wallhaven-yq8ljg.jpg
  blur: sm
  saturate: 50
  brightness: 75
  opacity: 50
