---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/


- search:
    provider: google
    # target: _blank

- glances:
    href: https://glances.shrishesha.duckdns.org/
    url: http://10.0.0.10:7300
    # username: user
    # password: pass
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk:
        - /pool
    diskUnits: bytes
    expanded: true
    label: Servarr

# - resources:
# #     cpu: true
# #     memory: true
#     disk:
#         - /pool
# #         - /mnt/ssd


# - openmeteo:
#     label: Kyiv # optional
#     latitude: 13.049394792841621
#     longitude: 80.10405459369967
#     timezone: Asia/Kolkata # optional
#     units: metric # or imperial
#     cache: 5 # Time in minutes to cache API responses, to stay within limits
#     format: # optional, Intl.NumberFormat options
#       maximumFractionDigits: 1